from datetime import datetime
from typing import Optional

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine


def get_engine(database_url: Optional[str] = None) -> Engine:
    url = database_url or "sqlite:///sales_analyzer.db"
    return create_engine(url, future=True)


def init_db(engine: Engine) -> None:
    with engine.begin() as conn:
        if engine.dialect.name == "postgresql":
            conn.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS query_logs (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at TEXT NOT NULL,
                        question TEXT NOT NULL,
                        response TEXT NOT NULL
                    )
                    """
                )
            )

            conn.execute(
                text(
                    """
                    DO $$
                    DECLARE
                        seq_name text;
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = current_schema()
                              AND table_name = 'query_logs'
                              AND column_name = 'id'
                              AND (
                                  is_identity = 'YES'
                                  OR column_default LIKE 'nextval(%'
                              )
                        ) THEN
                            IF NOT EXISTS (
                                SELECT 1
                                FROM pg_class
                                WHERE relkind = 'S'
                                  AND relname = 'query_logs_id_seq'
                            ) THEN
                                CREATE SEQUENCE query_logs_id_seq;
                            END IF;

                            ALTER TABLE query_logs
                            ALTER COLUMN id SET DEFAULT nextval('query_logs_id_seq');
                        END IF;

                        SELECT pg_get_serial_sequence('query_logs', 'id') INTO seq_name;
                        IF seq_name IS NOT NULL THEN
                            EXECUTE format(
                                'SELECT setval(%L, COALESCE((SELECT MAX(id) FROM query_logs), 0) + 1, false)',
                                seq_name
                            );
                        END IF;
                    END
                    $$;
                    """
                )
            )
        else:
            conn.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS query_logs (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        created_at TEXT NOT NULL,
                        question TEXT NOT NULL,
                        response TEXT NOT NULL
                    )
                    """
                )
            )


def log_query(engine: Engine, question: str, response: str) -> None:
    with engine.begin() as conn:
        conn.execute(
            text(
                """
                INSERT INTO query_logs (created_at, question, response)
                VALUES (:created_at, :question, :response)
                """
            ),
            {
                "created_at": datetime.utcnow().isoformat(timespec="seconds"),
                "question": question,
                "response": response,
            },
        )
